config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    get :search, on: :collection
    resource :profile, only: [:edit, :update]
  end

  resources :items do
    get :search, on: :collection
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  
  get '/items/hashtag/:name', to: "items#tag"
  get '/items/category/:id', to: "items#category"
  get '/items/like/:id', to: "items#like"
  get '/hashtags', to: "tags#search"
  get '/likes/user/:id', to: "likes#index"
  get '/comments/user/:id', to: "comments#index"
  get '/follows/user/:id', to: "users#follow"
  get '/followers/user/:id', to: "users#follower"
  get '/timeline/:id', to: "items#timeline"
  
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :lastname, :firstname, length: { maximum: 20 }
  validates :intro, length: { maximum: 80 }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :correct_user

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:image, :lastname, :firstname, :website, :intro).merge(user_id: current_user.id)
  end

  def set_profile
    @profile = Profile.find(current_user.id)
  end

  def correct_user
    redirect_to root_path unless user_signed_in? && @profile.user.id == current_user.id
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<%= render "shared/header" %>

<div class='profile-form-main'>
  <div class='profile-form'>
    <span class='profile-form-title'><%= current_user.username %></span>
  

    <%= form_with model: @profile, url: user_profile_path(current_user.id), local: true do |f| %>
      <%# エラーメッセージ %>

      <%# // エラーメッセージ %>
      
      <div class="profile-field-parent">
        <div class="profile-field-child">
          <%= f.text_field :lastname, class: "profile-input-child", id: "lastname", placeholder: "姓", maxlength: "20" %>      
          <%= f.text_field :firstname, class: "profile-input-child", id: "firstname", placeholder: "名", maxlength: "20" %>
        </div>
      </div>

      <div class="profile-field-parent">
        <div class="profile-field-child">
          <%= f.text_field :website, class: "profile-input", id: "website", placeholder: "サイト/ブログ" %>
        </div>
      </div>

      <div class="intro-field-parent">
        <div class="intro-field-child">
          <%= f.text_area :intro, class: "intro-input", id: "intro", placeholder: "自己紹介（80文字まで）", maxlength: "80" %>
        </div>
      </div>

      <div class="profile-image-parent">
        <div class="profile-image-child">
          <span>プロフィール画像</span>
          <%= f.file_field :image, class: 'profile-image', id:"profile-image" %>
        </div>
        <div id="image-list">
        </div>
      </div>
      
      <div class="profile-submit">
        <%= f.submit "プロフィールを編集する", class: "profile-submit-btn" %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<%= render "shared/header" %>

<div class='profile-form-main'>
  <div class='profile-form'>
    <span class='profile-form-title'><%= @user.username %></span>
  

    <%= form_with model: @profile, url: user_profiles_path(current_user), local: true do |f| %>
      <%# エラーメッセージ %>
      <%= render 'shared/error_messages', model: f.object %>
      <%# // エラーメッセージ %>
      
      <div class="profile-field-parent">
        <div class="profile-field-child">
          <%= f.text_field :lastname, class: "profile-input-child", id: "lastname", placeholder: "姓", maxlength: "20" %>      
          <%= f.text_field :firstname, class: "profile-input-child", id: "firstname", placeholder: "名", maxlength: "20" %>
        </div>
      </div>

      <div class="profile-field-parent">
        <div class="profile-field-child">
          <%= f.text_field :website, class: "profile-input", id: "website", placeholder: "サイト/ブログ" %>
        </div>
      </div>

      <div class="intro-field-parent">
        <div class="intro-field-child">
          <%= f.text_area :intro, class: "intro-input", id: "intro", placeholder: "自己紹介", maxlength: "200" %>
        </div>
      </div>

      <div class="profile-image-parent">
        <div class="profile-image-child">
          <span>プロフィール画像</span>
          <%= f.file_field :image, id:"profile-image" %>
        </div>
        <div id="image-list"></div>
      </div>
      
      <div class="profile-submit">
        <%= f.submit "プロフィールを編集する", class: "profile-submit-btn" %>
      </div>
      
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>