config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    get :search, on: :collection
    resource :profile, only: [:edit, :update]
  end

  resources :items do
    get :search, on: :collection
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  
  get '/items/hashtag/:name', to: "items#tag"
  get '/items/category/:id', to: "items#category"
  get '/items/like/:id', to: "items#like"
  get '/hashtags', to: "tags#search"
  get '/likes/user/:id', to: "likes#index"
  get '/comments/user/:id', to: "comments#index"
  get '/follows/user/:id', to: "users#follow"
  get '/followers/user/:id', to: "users#follower"
  get '/timeline/:id', to: "items#timeline"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one  :profile, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_items, through: :comments, source: :item
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  paginates_per 10

  validates :username, presence: true, uniqueness: { case_sensitive: true }, length: { maximum: 14 }

  USERNAME_REGEX = /\A[a-zA-Z0-9]+\z/.freeze
  validates_format_of :username, with: USERNAME_REGEX, message: 'は半角英数で入力してください'
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英数のみで両方含めてください'

  def already_liked?(item)
    likes.exists?(item_id: item.id)
  end

  def follow(other_user)
    relationships.find_or_create_by(follow_id: other_user.id) unless self == other_user
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.search(search)
    if search != ''
      User.where('username LIKE(?)', "%#{search}%")
    else
      User.all
    end
  end

  def self.guest
    find_by(username: 'guest')
  end

  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification =current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
    
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  def check_guest
    redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません' if params[:user][:email].downcase == 'guest@example.com'
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_guest, only: [:update, :destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super

    resource.build_profile
    resource.profile.intro = 'プロフィールを編集しよう！'
    resource.profile.image.attach(io: File.open('public/images/human_icon.png'), filename: 'human_icon.png')
    resource.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def after_sign_up_path_for(_resource)
    root_path
  end

  def check_guest
    redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません' if resource.email == 'guest@example.com'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました'
  end

  def after_sign_in_path_for(_resource)
    root_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user_follower, only: :follower

  def show
    @user = User.find(params[:id])
    @items = @user.items.open.order('created_at DESC').page(params[:page])
    @user_items = @user.items.order('created_at DESC').page(params[:page])
    @status_items = @user.items.where(created_at: 6.days.ago.beginning_of_day..Time.zone.now.end_of_day)
    @all_items = @user.items
  end

  def search
    @users = User.search(params[:keyword]).order('created_at DESC').page(params[:page])
    if user_signed_in?
      @user = current_user
      @my_items = Item.where(user_id: current_user.id).order('created_at DESC')
    end
  end

  def follow
    @follow_user = User.find(params[:id])
    @users = @follow_user.followings.order('relationships.created_at DESC').page(params[:page])
    if user_signed_in?
      @user = current_user
      @my_items = Item.where(user_id: current_user.id).order('created_at DESC')
    end
  end

  def follower
    @follower_user = User.find(params[:id])
    @users = @follower_user.followers.order('relationships.created_at DESC').page(params[:page])
    if user_signed_in?
      @user = current_user
      @my_items = Item.where(user_id: current_user.id).order('created_at DESC')
    end
  end

  private

  def correct_user_follower
    redirect_to root_path unless user_signed_in? && params[:id] = current_user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if current_user.following?(user) %>
  <%= form_with model: current_user.relationships.find_by(follow_id: user.id), remote: true, method: :delete do |f| %>
    <%= hidden_field_tag :follow_id, user.id %>
    <%= f.submit 'フォロー ✔︎', class: 'userpage-followed-btn' %>
  <% end %>
<% else %>
  <%= form_with model: current_user.relationships.build, remote: true do |f| %>
    <%= hidden_field_tag :follow_id, user.id %>
    <%= f.submit 'フォロー', class: 'userpage-follow-btn' %>
  <% end %>
<% end %>

app/views/users/_usercard.html.erb
<div class='user-card'>
  <% if @user == current_user %>
    <div class='user-menu-btn', id='user-menu-btn'>
      …
    </div>
    <div class='user-menu hidden', id='user-menu'>
      <div class='user-menu-content'>
        <%= link_to "プロフィール編集", edit_user_profile_path(current_user.id), class: "user-menu-1" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "user-menu-2"  %>
      </div>
    </div>
  <% end %>
  <%= image_tag @user.profile.image.variant(resize_to_fill: [128, 128]), class:"main-avatar"%>
  <div class='user-name'>
    <%= @user.username%>
  </div>
  <div class='user-status'>
    <div class='user-status-top'>
      <div class='user-status-nums'>
        <span class='status-title'>投稿</span>
        <span class='status-number'><%= @user.items.count %></span>
      </div>
      <div class='user-status-nums'>
        <span class='status-title'>コメント</span>
        <%= link_to @user.comments.count, "/comments/user/#{@user.id}", class: 'status-number' %>
      </div>
      <div class='user-status-nums'>
        <span class='status-title'>いいね</span>
        <%= link_to @user.likes.count, "/likes/user/#{@user.id}", class: 'status-number' %>
      </div>
    </div>
    <div class='user-status-bottom'>
      <div class='user-status-nums'>
        <span class='status-title'>フォロー</span>
        <%= link_to @user.followings.count, "/follows/user/#{@user.id}", class: 'status-number' %>
      </div>
      <%# フォロワー数はログインユーザーのみ表示%>
      <div class='user-status-nums'>
        <% if @user == current_user%>
          <span class='status-title'>フォロワー</span>
          <%= link_to @user.followers.count, "/followers/user/#{@user.id}", class: 'status-number' %>
        <% else %>
          <span class='status-title'>フォロワー</span>
          <span class='status-number'>-</span>
        <% end %>
      </div>
      <%# // フォロワー数はログインユーザーのみ表示%>
    </div>
  </div>
</div>

app/views/users/_userlist.html.erb
<% @users.each do |user| %>
  <li class='item-list'>
    <%= link_to user_path(user.id) do %>
      <div class='list-profile-content'>
        <%= image_tag user.profile.image.variant(resize_to_fill: [128, 128]), class:'list-avatar'%>
      </div>
    <% end %>
    <div class='user-list-main-content'>
      <div class='list-title-content'>
        <%= link_to "#{user.username}", user_path(user.id) %>
      </div>
      <div class='list-cate-tag-content'>
        <div class='list-profile-title'>
          Profile
        </div>
        <div class='list-tag'>
          <p><%= user.profile.intro %></p>
        </div>
      </div>
      <div class='user-list-detail-content'>
        <div class='user-list-detail'>
          <div class='list-like-comment'>
            <div class='list-like-count'>
              <%= image_tag "icon-new.png", class: "icon-new" %>
              <%= user.items.count%>
            </div>
            <div class='list-like-count'>
              <%= image_tag "icon-like.png", class: 'list-like-icon'%>
              <%= user.likes.count%>
            </div>
            <div class='user-list-comment-count'>
              <%= image_tag "icon-comment.png", class: 'list-comment-icon'%>
              <%= user.comments.count %>
            </div>
            <%= image_tag 'human_icon.png', size: '15x15' %>
            <div class='list-follow-count'>
              <%= user.relationships.count %>
            </div>
          </div>
          <div class='user-list-created-at'>
            <%= user.created_at.strftime('20%y年%m月から利用') %>
          </div>
          <div class='user-list-created-at-small'>
            <%= user.created_at.strftime('20%y年%m月') %>
          </div>
        </div>
      </div>
    </div>
  </li>
<% end %>

app/views/users/follow.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# Left-side %>
  <div class='top-left-content'>   
    <div class='whose-item-list-navi'>
      <%= image_tag @follow_user.profile.image.variant(resize_to_fill: [128, 128]), class: 'whose-user-avatar'%>
      <p><%= @follow_user.username%> 's follow</p>
    </div>
    <%# @users リスト展開 %>
    <div id='user-pagenate'>
      <%= render 'userlist'%>
    </div>
    <%= link_to_next_page @users, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <%# // @users リスト展開 %>   
  </div>
  <%# // Left-side %>
  
  <%# Right-side %>
  <%= render 'shared/right_side' %>
  <%# // Right-side %>

</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/users/follow.js.erb
$('#user-pagenate').append("<%= escape_javascript(render 'userlist', object: @users) %>")
$("#more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@users, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')
) %>");

app/views/users/follower.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# Left-side %>
  <div class='top-left-content'>   
    <div class='whose-item-list-navi'>
      <%= image_tag @follower_user.profile.image.variant(resize_to_fill: [128, 128]), class: 'whose-user-avatar'%>
      <p><%= @follower_user.username%> 's follower</p>
    </div>
    <%# @users リスト展開 %>
    <div id='user-pagenate'>
      <%= render 'userlist'%>
    </div>
    <%= link_to_next_page @users, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <%# // @users リスト展開 %>   
  </div>
  <%# // Left-side %>
  
  <%# Right-side %>
  <%= render 'shared/right_side' %>
  <%# // Right-side %>

</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/users/follower.js.erb
$('#user-pagenate').append("<%= escape_javascript(render 'userlist', object: @users) %>")
$("#more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@users, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')
) %>");

app/views/users/search.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# Left-side %>
  <div class='top-left-content'>

    <%# Search-Contents %>
    <%= render 'shared/search_contents' %>
    <%# // Search-Contents %>

    <div class='item-list-navi'>
      <p>👤「 <%= params[:keyword] %> 」の検索結果</p>
    </div>

    <%# @users リスト展開 %>
    <div id='user-pagenate'>
      <%= render 'userlist'%>
    </div>
    <%= link_to_next_page @users, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <%# // @users リスト展開 %>

  </div>
  <%# // Left-side %>
  
  <%# Right-side %>
  <%= render 'shared/right_side' %>
  <%# // Right-side %>

</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/users/search.js.erb
$('#user-pagenate').append("<%= escape_javascript(render 'userlist', object: @users) %>")
$("#more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@users, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')
) %>");

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class='user-main'>

  <div class='user-right-content'>

    <%# user-card部分%>
    <%= render "usercard" %>
    <%# // user-card部分%>

    <div class="second-user-card">
   
      <div class='user-intro'>
        <%= @user.profile.intro %>
      </div>

      <% if @user.profile.website && @user.profile.website != '' %>
        <div class='user-website-content'>
          <span class='user-website-mark'>〄</span>
          <%= link_to @user.profile.website, "#{ @user.profile.website }",  class: 'user-website' %>
        </div>
      <% end%>
      
      <%# フォローボタン%>
      <% if user_signed_in? && current_user.id.to_s != params[:id]  %>
        <div id="follow-btn-userpage">
          <%= render 'follow', user: @user %>
        </div>
      <% end %>
      <%# // フォローボタン%>

      <% unless user_signed_in? %>
        <%= link_to "✔︎ ユーザー登録をして#{@user.username}さんをフォローしませんか？", new_user_registration_path, class: 'userpage-regist-suggest-btn'%>
      <% end %>

    </div>
  </div>

  <div class='user-left-content'>
    <%# if @user == current_user %>
      <div class="user-analytics">
        <span class='activity'>Activity</span>
        <div class='weekly-count'>
          <% 7.times do |x|%>
            <% if @user.items.exists?(['created_at LIKE ?', "%#{(Date.today - 6 + x)}%"])%>
              <div class='weekly-count-day'>
                <span><%= (Date.today - 6 + x).strftime('%a') %></span>
                <span><%= (Date.today - 6 + x).strftime('%e') %></span>
              </div>
            <% else %>
              <div class='weekly-count-day-off'>
                <span><%= (Date.today - 6 + x).strftime('%a') %></span>
                <span><%= (Date.today - 6 + x).strftime('%e') %></span>
              </div>
            <% end%>
          <% end %>
        </div>
        <span class='status'>7days</span>
        <div class='status-count'>
          <div class='status-count-block'>
            <span>Open</span>
            <%= @status_items.open.count  %>
          </div>
          <div class='status-count-block'>
            <span>Closed</span>
            <%= @status_items.closed.count %>
          </div>
           <div class='status-count-block'>
            <span>Book</span>
            <%= "#{@status_items.where(category_id: 1).count * 100 / @status_items.count rescue 0 }%" %>
          </div>
          <div class='status-count-block'>
            <span>Youtube</span>
            <%= "#{@status_items.where(category_id: 2).count * 100 / @status_items.count rescue 0}%" %>
          </div>
          <div class='status-count-block'>
            <span>SNS</span>
            <%= "#{@status_items.where(category_id: 3).count * 100 / @status_items.count rescue 0}%" %>
          </div>
          <div class='status-count-block'>
            <span>Event</span>
            <%= "#{@status_items.where(category_id: 4).count * 100 / @status_items.count rescue 0}%" %>
          </div>
          <div class='status-count-block'>
            <span>Memo</span>
            <%= "#{@status_items.where(category_id: 5).count * 100 / @status_items.count rescue 0}%" %>
          </div>
        </div>
        <span class='status'>Total</span>
        <div class='status-count'>
          <div class='status-count-block'>
            <span>Open</span>
            <%= @all_items.open.count  %>
          </div>
          <div class='status-count-block'>
            <span>Closed</span>
            <%= @all_items.closed.count %>
          </div>
           <div class='status-count-block'>
            <span>Book</span>
            <%= "#{@all_items.where(category_id: 1).count * 100 / @all_items.count rescue 0 }%" %>
          </div>
          <div class='status-count-block'>
            <span>Youtube</span>
            <%= "#{@all_items.where(category_id: 2).count * 100 / @all_items.count rescue 0}%" %>
          </div>
          <div class='status-count-block'>
            <span>SNS</span>
            <%= "#{@all_items.where(category_id: 3).count * 100 / @all_items.count rescue 0}%" %>
          </div>
          <div class='status-count-block'>
            <span>Event</span>
            <%= "#{@all_items.where(category_id: 4).count * 100 / @all_items.count rescue 0}%" %>
          </div>
          <div class='status-count-block'>
            <span>Memo</span>
            <%= "#{@all_items.where(category_id: 5).count * 100 / @all_items.count rescue 0}%" %>
          </div>
        </div>
      </div>
    <%# end %>

    <%# @items リスト展開 %>
    <% if @user == current_user %>
      <div id='users-item-pagenate'>
        <%= render "shared/users-item-list"%>
      </div>
      <%= link_to_next_page @user_items, 'もっと見る', remote: true, class: 'more-link', id: 'users-more-link' %>
    <% else %>
      <div id='item-pagenate'>
        <%= render "shared/item-list" %>
      </div>
      <%= link_to_next_page @items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <% end %>
    <%# // @items リスト展開 %>

  </div>
</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/users/show.js.erb
$('#users-item-pagenate').append("<%= escape_javascript(render 'shared/users-item-list', object: @user_items) %>")
$("#users-more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@user_items, 'もっと見る', remote: true, class: 'more-link', id: 'users-more-link')
) %>");

$('#item-pagenate').append("<%= escape_javascript(render 'shared/item-list', object: @items) %>")
$("#more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')
) %>");