config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    get :search, on: :collection
    resource :profile, only: [:edit, :update]
  end

  resources :items do
    get :search, on: :collection
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  
  get '/items/hashtag/:name', to: "items#tag"
  get '/items/category/:id', to: "items#category"
  get '/items/like/:id', to: "items#like"
  get '/hashtags', to: "tags#search"
  get '/likes/user/:id', to: "likes#index"
  get '/comments/user/:id', to: "comments#index"
  get '/follows/user/:id', to: "users#follow"
  get '/followers/user/:id', to: "users#follower"
  get '/timeline/:id', to: "items#timeline"
  
end

app/views/shared/_command.html.erb
<% if user_signed_in? %>
  <div class='smartphone-command-bar'>
    <%= link_to image_tag("icon-home.png", class: "command-home"), "/"%>
    <%= link_to image_tag("icon-tl.png", class: "command-tl"), "/timeline/#{current_user.id}" %>
    <%= link_to image_tag("icon-new.png", class: "command-new"), new_item_path %>
    <%= link_to image_tag(current_user.profile.image.variant(resize_to_fill: [128, 128]), class: "command-avatar"), user_path(current_user.id) %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class='header'>
  <div class='left-header'>
    <%= link_to image_tag("output_app_logo.png", class: "output_app_logo"), "/"%> 
  </div>

  <%# ログイン有無の条件分岐 %>
  <div class='right-header'>
    <% if user_signed_in? %>
      <ul class='signed-in-list'>
        <li><%= link_to image_tag("icon-home-brown.png", class: "icon-home-brown"), '/' %></li>
        <li><%= link_to 'TL', "/timeline/#{current_user.id}", class:"tl-list-btn" %></li>
        <%= link_to "/likes/user/#{current_user.id}" do %>
          <li class="like-list-btn">
            <%= image_tag "icon-like-white.png", class: "icon-like-white" %>
            <p>LIKE</p>
          </li>
        <% end %>
        <%= link_to new_item_path do %>
          <li class="new-item-btn">
            <%= image_tag "icon-new-white.png", class: "icon-new-white" %>
            <p>NEW</p> 
          </li>
        <% end %>
        <% if unchecked_notifications.any? %>
        <li><%= link_to image_tag("icon-bell-red.png", class: "icon-bell"), notifications_path %></li>
        <% else %>
        <li><%= link_to image_tag("icon-bell-white.png", class: "icon-bell"), notifications_path %></li>
        <% end %>
        <li><%= link_to image_tag(current_user.profile.image.variant(resize_to_fill: [128, 128]), class: "header-avatar"), user_path(current_user.id) %></li>
        <li><%= link_to image_tag("icon-like-brown.png", class: "like-list-btn-small"), "/likes/user/#{current_user.id}" %>
      </ul>
    <% else %>
      <ul class='not-signed-in-list'>
        <li><%= link_to 'ログイン', new_user_session_path, class: "sign-in-btn" %></li>
      </ul>
    <% end %>
  </div>
  <%# // ログイン有無の条件分岐 %>

</header>

app/views/shared/_item-list.html.erb
<% @items.each do |item| %>
  <li class='item-list'>
    <%= link_to user_path(item.user.id) do %>
      <div class='list-profile-content'>
        <%= image_tag item.user.profile.image.variant(resize_to_fill: [128, 128]), class:'list-avatar'%>
        <span class='list-username'><%= item.user.username %></span>
      </div>
    <% end %>

    <% if item.image.attached? %>
    <div class='list-main-content-b'>
    <% else %>
    <div class='list-main-content-a'>
    <% end %>
      <div class='list-title-content'>
        <p><%= link_to "#{item.title}", item_path(item.id) %></p>
      </div>
      <div class='list-cate-tag-content'>
        <div class='list-category'>
          <%= item.category.name %>
        </div>
        <div class='list-tag'>
          <p><%= item.tagbody %></p>
        </div>
      </div>
      <div class='list-detail-content'>
        <div class='list-detail'>
          <div class='list-like-comment'>
            <div class='list-like-count'>
              <%= image_tag "icon-like.png", class: 'list-like-icon'%>
              <%= Like.where(item_id: item.id).count %>
            </div>
            <div class='list-comment-count'>
              <%= image_tag "icon-comment.png", class: 'list-comment-icon'%>
              <%= Comment.where(item_id: item.id).count %>
            </div>
          </div>
          <div class='list-created-at'>
            <%= "#{time_ago_in_words(item.created_at)}前" %>
          </div>
        </div>
      </div>
    </div>
    <% if item.image.attached? %>
      <div class='list-image-content'>      
        <%= image_tag item.image.variant(resize_to_fill: [61.5, 82]), class: 'list-image'%>
      </div>
    <% end %>
  </li>
<% end %>

app/views/shared/_my-item-list.html.erb
<% @my_items.first(8).each do |item| %>
  <li class='my-item-list'>
    <div class='my-list-main-content'>
      <div class='my-list-cate-detail-content'>     
        <div class='my-list-category'>
          <%= item.category.name %>
        </div>
        <% if item.status_before_type_cast == 1 %>
          <div class='my-list-open'>
            open
          </div>
        <% else %>
          <div class='my-list-closed'>
            closed
          </div>
        <% end %>
      </div>
       <div class='my-list-title-content'>
        <p><%= link_to "#{item.title}", item_path(item.id) %></p>
      </div>
      <div class='my-list-detail-content'>
        <div class='list-like-comment'>
            <div class='my-list-like-count'>
              <%= image_tag "icon-like.png", class: 'my-list-like-icon'%>
              <%= Like.where(item_id: item.id).count %>
            </div>
            <div class='my-list-comment-count'>
              <%= image_tag "icon-comment.png", class: 'my-list-comment-icon'%>
              <%= Comment.where(item_id: item.id).count %>
            </div>
          </div>
        <div class='my-list-created-at'>
          <%= "#{time_ago_in_words(item.created_at)}前" %>
        </div>  
      </div>   
    </div>
  </li>
<% end %>

app/views/shared/_right_side.html.erb
<% if user_signed_in? %>
  <div class='top-right-content'>
    <div class='top-user-card'>
      <%# 共通user-card部分%>
      <%= render "shared/toppage_usercard" %>
      <%# // 共通user-card部分%> 
    </div>

    <div class='top-my-output'>
      <div class='item-list-navi'>
        <p>My Output</p>
      </div>
      <%# @my_items リスト展開 %>
      <%= render "shared/my-item-list" %>
      <%# // @my_items リスト展開 %>
    </div>
  </div>
<% else %>
  <div class='top-right-content-unlogin'>
    <p>✍️ 開発者メモ</p>
    <p>>>> コンテンツ開発中 >>></P>
  </div>
<% end %>

app/views/shared/_search_contents.html.erb
<div class='search-bar'>
  <div class='search-bar-left'>
    <select class='search-menu' id='search-menu'>
      <option value="0">＃</option>
      <option value="1">✏︎</option>
      <option value="2">👤</option>
    </select>
  </div>
  <div class='search-bar-right'>
    <%= form_with(url: hashtags_path, local: true, method: :get, class:'search-form', id:'search-form') do |form| %>
      <%= form.text_field :keyword, class: "search-input", id: "search-input", placeholder: "ハッシュタグで検索" %>
      <%= image_submit_tag "icon-search.png", class: "search-btn" %>
    <% end %>
  </div>  
</div>

<div class='search-category'>
  <ul class='search-category-list'>
    <%=link_to "/items/category/1" do %>
      <li class='search-category-btn'>本</li>
    <% end %>
    <%=link_to "/items/category/2" do %>
      <li class='search-category-btn'>Youtube</li>
    <% end %>
    <%=link_to "/items/category/3" do %>
      <li class='search-category-btn'>記事/SNS</li>
    <% end %>
    <%=link_to "/items/category/4" do %>
      <li class='search-category-btn'>イベント</li>
    <% end %>
    <%=link_to "/items/category/5" do %>
      <li class='search-category-btn'>メモ</li>
    <% end %>
  </ul>
</div>

app/views/shared/_second-header.html.erb
<header class="second-header">
  <div class="second-logo-box">
    <%= link_to image_tag("output_app_logo.png", class: "output_app_logo"), "/"%>
  </div>
</header>

app/views/shared/_show_follow.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー ✔︎', class: 'show-unfollow-btn' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー', class: 'show-follow-btn' %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_sign_top.html.erb
<div class= "sign-top-content">
  Output App へようこそ
</div>

app/views/shared/_test.html.erb
<%# デザイン募集 >
<div class= "sign-top-content">
  <div class='pr'>
    <span>デ</span>
    <span>ザ</span>
    <span>イ</span>
    <span>ン</span>
    <span>を</span>
    <span>考</span>
    <span>え</span>
    <span>て</span>
  </div>
  <div class='pr'>
    <span>く</span>
    <span>れ</span>
    <span>る</span>
    <span>人</span>
    <span>大</span>
    <span>募</span>
    <span>集</span>
  </div>
  <a href="https://twitter.com/gonblog">>> 運営Twitterアカウント</a>
</div>
<%# デザイン募集 %>

app/views/shared/_toppage_usercard.html.erb
<div class='toppage-user-card'>
  <%= image_tag @user.profile.image.variant(resize_to_fill: [128, 128]), class:"main-avatar"%>
  <div class='user-name'>
    <%= @user.username%>
  </div>
  <div class='user-status'>
    <div class='user-status-top'>
      <div class='user-status-nums'>
        <span class='status-title'>投稿</span>
        <span class='status-number'><%= @user.items.count %></span>
      </div>
      <div class='user-status-nums'>
        <span class='status-title'>コメント</span>
        <%= link_to @user.comments.count, "/comments/user/#{@user.id}", class: 'status-number' %>
      </div>
      <div class='user-status-nums'>
        <span class='status-title'>いいね</span>
        <%= link_to @user.likes.count, "/likes/user/#{@user.id}", class: 'status-number' %>
      </div>
    </div>
    <div class='user-status-bottom'>
      <div class='user-status-nums'>
        <span class='status-title'>フォロー</span>
        <%= link_to @user.followings.count, "/follows/user/#{@user.id}", class: 'status-number' %>
      </div>
      <div class='user-status-nums'>
        <span class='status-title'>フォロワー</span>
        <%= link_to @user.followers.count, "/followers/user/#{@user.id}", class: 'status-number' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_userpage_follow.html.erb
<% if current_user.following?(user) %>
  <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :follow_id, user.id %>
    <%= f.submit 'フォロー ✔︎', class: 'userpage-unfollow-btn' %>
  <% end %>
<% else %>
  <%= form_for(current_user.relationships.build) do |f| %>
    <%= hidden_field_tag :follow_id, user.id %>
    <%= f.submit 'フォロー', class: 'userpage-follow-btn' %>
  <% end %>
<% end %>

app/views/shared/_users-item-list.html.erb
<% @user_items.each do |item| %>
  <li class='item-list'>
    <%= link_to user_path(item.user.id) do %>
      <div class='list-profile-content'>
        <%= image_tag item.user.profile.image.variant(resize_to_fill: [128, 128]), class:'list-avatar'%>
        <span class='list-username'><%= item.user.username %></span>
      </div>
    <% end %>
    <div class='users-list-main-content'>
      <div class='users-list-title-content'>
        <% if item.status_before_type_cast == 1 %>
          <div class='users-list-open'>
            open
          </div>
        <% else %>
          <div class='users-list-closed'>
            closed
          </div>
        <% end %>
        <p><%= link_to "#{item.title}", item_path(item.id) %></p>
      </div>
      <div class='list-cate-tag-content'>
        <div class='list-category'>
          <%= item.category.name %>
        </div>
        <div class='list-tag'>
          <p><%= item.tagbody %></p>
        </div>
      </div>
      <div class='list-detail-content'>
        <div class='list-detail'>
          <div class='list-like-comment'>
            <div class='list-like-count'>
              <%= image_tag "icon-like.png", class: 'list-like-icon'%>
              <%= Like.where(item_id: item.id).count %>
            </div>
            <div class='list-comment-count'>
              <%= image_tag "icon-comment.png", class: 'list-comment-icon'%>
              <%= Comment.where(item_id: item.id).count %>
            </div>
          </div>
          <div class='list-created-at'>
            <%= "#{time_ago_in_words(item.created_at)}前" %>
          </div>
        </div>
      </div>
    </div>
  </li>
<% end %>