config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show] do
    get :search, on: :collection
    resource :profile, only: [:edit, :update]
  end

  resources :items do
    get :search, on: :collection
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  
  get '/items/hashtag/:name', to: "items#tag"
  get '/items/category/:id', to: "items#category"
  get '/items/like/:id', to: "items#like"
  get '/hashtags', to: "tags#search"
  get '/likes/user/:id', to: "likes#index"
  get '/comments/user/:id', to: "comments#index"
  get '/follows/user/:id', to: "users#follow"
  get '/followers/user/:id', to: "users#follower"
  get '/timeline/:id', to: "items#timeline"
  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, source: :user
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags
  belongs_to_active_hash :category
  has_one_attached :image
  has_many :notifications, dependent: :destroy

  enum status: { closed: 0, open: 1 }
  paginates_per 10

  with_options presence: true do
    validates :title, length: { maximum: 40 }
    validates :body, length: { maximum: 100_000 }
    validates :category_id
  end
  validates :tagbody, length: { maximum: 60 }
  validates :tagbody, format: { without: /[０-９]/, message: 'の数字は半角で入力してください' }
  validates :tagbody, format: { without: /＃/, message: ' # は半角で入力してください' }
  validates :tagbody, format: { without: /♯/, message: ' # は半角で入力してください' }

  after_create do
    item = Item.find_by(id: id)
    tags = tagbody.scan(/#[\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |tag|
      t = Tag.find_or_create_by(name: tag.delete('#'))
      item.tags << t
    end
  end

  before_update do
    item = Item.find_by(id: id)
    item.tags.clear
    tags = tagbody.scan(/#[\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    tags.uniq.map do |tag|
      t = Tag.find_or_create_by(name: tag.delete('#'))
      item.tags << t
    end
  end

  def self.search(search)
    if search != ''
      Item.where('title LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end

  def create_notification_like(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and item_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        item_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(item_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      item_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show]
  before_action :set_user_items, only: [:index, :tag, :category, :search, :timeline]
  before_action :correct_user_new, only: :new
  before_action :correct_user_edit, only: :edit
  before_action :correct_user_show, only: :show
  before_action :correct_user_timeline, only: :timeline

  def index
    @items = Item.open.order('created_at DESC').page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.order('created_at DESC')
    @like_count = Like.where(item_id: @item.id).count
  end

  def tag
    @tag = Tag.find_by(name: params[:name])
    @items = @tag.items.open.order('created_at DESC').page(params[:page])
  end

  def category
    @item = Item.find_by(category_id: params[:id])
    @items = Item.open.where(category_id: params[:id]).order('created_at DESC').page(params[:page])
  end

  def search
    @items = Item.open.search(params[:keyword]).order('created_at DESC').page(params[:page])
  end

  def like
    @liked_item = Item.find(params[:id])
    @users = @liked_item.liked_users.order('likes.created_at DESC').page(params[:page])
    if user_signed_in?
      @user = current_user
      @my_items = Item.where(user_id: current_user.id).order('created_at DESC')
    end
  end

  def timeline
    @followings = current_user.followings
    @items = Item.where(user_id: @followings).or(Item.where(user_id: current_user.id)).order('created_at DESC').open.page(params[:page])
  end

  private

  def item_params
    params.require(:item).permit(:title, :tagbody, :body, :url, :status, :category_id, :image).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_user_items
    if user_signed_in?
      @user = current_user
      @my_items = Item.where(user_id: current_user.id).order('created_at DESC')
    end
  end

  def correct_user_new
    redirect_to new_user_registration_path unless user_signed_in?
  end

  def correct_user_edit
    redirect_to root_path unless user_signed_in? && @item.user.id == current_user.id
  end

  def correct_user_show
    if @item.closed?
      redirect_to root_path unless @item.user == current_user
    end
  end

  def correct_user_timeline
    redirect_to root_path unless user_signed_in? && params[:id] = current_user.id
  end

end

app/helpers/items_helper.rb
module ItemsHelper
  def render_with_tags(tagbody)
    tagbody.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/) { |word| link_to word, "/items/hashtag/#{word.delete('#')}" }.html_safe
  end
end

app/views/items/_comment.html.erb
<div class='comment-info'>
  <%= image_tag "icon-comment.png", class: 'info-icon-comment'%>
  コメント
</div>
<% if user_signed_in? %>
  <div class='comment-input'>
    <%= form_with model: @comment, url: item_comments_path(@item.id), local: true do |f| %>
      <div class='comment-btn-box'>
        <div class='comment-btn-box-left'>
          <%= image_tag current_user.profile.image.variant(resize_to_fill: [128, 128]), class:'show-top-avatar'%>
          <span class='show-top-username'><%= current_user.username %></span>
        </div>
        <%= f.submit 'コメントする', class:'comment-btn'%>
      </div>
      <div class='comment-text-box'>
        <%= f.text_area :message, class:"comment-text", id:"comment-text", placeholder:"テキストを入力", maxlength:"10000" %>
      </div>
    <% end %>
  </div>
<% else %>
  <span><%= link_to 'ユーザー登録', new_user_registration_path %>をしてコメントを書こう！</span>
<% end %>

<% @comments.each do |comment| %>
  <div class="comment-content">
    <div class="comment-btn-box">
      <div class="comment-btn-box-left">
        <%= link_to image_tag(comment.user.profile.image.variant(resize_to_fill: [128, 128]), class: 'show-top-avatar'), user_path(comment.user.id) %>
        <%= link_to comment.user.username, user_path(comment.user.id), class: 'show-top-username' %>
      </div>
      <div class="comment-btn-box-right">
        <% if comment.user == current_user %>
          <%= link_to '削除', "/items/#{@item.id}/comments/#{comment.id}", method: :delete,  class: "comment-delete-btn" %>
        <% end %>
        <%= "#{time_ago_in_words(comment.created_at)}前" %>
      </div>
    </div>
    <div class="comment-message">
      <%= markdown(comment.message).html_safe %>
    </div>
    <div class="comment-bottom-border-box">
      <div class='comment-bottom-border'>
      </div>
    </div>
  </div>
<% end %>

app/views/items/_follow.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with model: current_user.relationships.find_by(follow_id: user.id), remote: true, method: :delete do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー ✔︎', class: 'show-unfollow-btn' %>
    <% end %>
  <% else %>
    <%= form_with model: current_user.relationships.build, remote: true do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォロー', class: 'show-follow-btn' %>
    <% end %>
  <% end %>
<% end %>

app/views/items/_guest.html.erb
<div class='guest-login-box'>
  <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class:'guest-login-btn' %>
  <%= link_to 'ユーザー登録', new_user_registration_path, class: "sign-up-btn" %>
</div>

app/views/items/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.already_liked?(@item) %>
    <%= link_to item_like_path(@item.id), method: :delete, remote: true do %>
      <div class='show-top-liked-btn'>
        <span>LIKED ✔︎ <%= @like_count %></span>
      </div>
    <% end %>
  <% else %>
     <%= link_to item_likes_path(@item.id), method: :post, remote: true do %>
      <div class='show-top-like-btn'>
        <span>LIKE ✔︎ <%= @like_count %></span>
      </div>
    <% end %>
  <% end %>
<% else %>
  <div class='show-top-like-onlydisplay'>
    <span>LIKE ✔︎ <%= @like_count %></span>
  </div>
<% end %>

app/views/items/category.js.erb
$('#item-pagenate').append("<%= escape_javascript(render 'shared/item-list', object: @items) %>")
$("#more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')
) %>");

app/views/items/index.html.erb
<%= render "shared/header" %>


<%# ゲストログイン用コンテンツ%>
<% unless user_signed_in?%>
  <%= render 'guest'%>
<% end %>
<%# // ゲストログイン用コンテンツ%>

<div class='main'>

  <%# if user_signed_in? %>
    <%# if @user.username == 'guest' %>
      <%# ゲストログイン中！機能が制限されています。 %>
    <%# end %>
  <%# end %>

  <%# Left-side %>
  <div class='top-left-content'>

    <%# Search-Contents %>
    <%= render 'shared/search_contents' %>
    <%# // Search-Contents %>

    <div class='top-infomation'>
      <%= link_to ' >> 初めてご利用の方へ', '/items/1' %>
    </div>

    <div class='item-list-navi'>
      <p>Trend</p>
    </div>

    <%# @items リスト展開 %>
    <div id='item-pagenate'>
      <%= render "shared/item-list" %>
    </div>
    <%= link_to_next_page @items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <%# // @items リスト展開 %>   
    
  </div>
  <%# // Left-side%>

  
  <%# Right-side %>
  <%= render 'shared/right_side' %>
  <%# // Right-side %>

</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/items/index.js.erb
$('#item-pagenate').append("<%= escape_javascript(render 'shared/item-list', object: @items) %>")
$("#more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')
) %>");

app/views/items/like.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# Left-side %>
  <div class='top-left-content'>   
    <div class='liked-item-list-navi'>
      <span><%= @liked_item.title %></span>
      <p>LIKEしたユーザー</p>
    </div>
    <%# @users リスト展開 %>
    <div id='user-pagenate'>
      <%= render 'users/userlist'%>
    </div>
    <%= link_to_next_page @users, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <%# // @users リスト展開 %>   
  </div>
  <%# // Left-side %>
  
  <%# Right-side %>
  <%= render 'shared/right_side' %>
  <%# // Right-side %>

</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render "shared/header" %>

<%= form_with model:@item, url: '/items', local: true do |f| %>
  <div class='main'>
    <div class='new-content'>    
      <%# エラーメッセージ %>
      <%= render 'shared/error_messages', model: f.object %>
      <%# // エラーメッセージ %>
      <div class='caption-area'>
        <div class='first-box'>
          <%= f.text_field :title, class:'caption-input', id:'item-title', placeholder:'タイトル', maxlength: '40' %>
        </div>
        <div class='second-box'>
          <div class='second-box-left'>
            <ul class='category-list'>
              <li>
                <%= f.radio_button :category_id, '1', class: 'category-radio-btn' %>
                <label>本</label>
              </li>
              <li>
                <%= f.radio_button :category_id, '2', class: 'category-radio-btn' %>
                <label>Youtube</label>
              </li>
              <li>
                <%= f.radio_button :category_id, '3', class: 'category-radio-btn' %>
                <label>記事/SNS</label>
              </li>
              <li>
                <%= f.radio_button :category_id, '4', class: 'category-radio-btn' %>
                <label>イベント</label>
              </li>
              <li>
                <%= f.radio_button :category_id, '5', class: 'category-radio-btn' %>
                <label>メモ</label>
              </li>
            </ul>
          </div>
          <div class='second-box-right'>
            <%= f.text_field :tagbody, class:'caption-input', id:'item-tagbody', placeholder:'#ハッシュタグ', maxlength: '60' %>
          </div>
        </div>
        <div class='third-box'>
          <div class='third-box-left'>
            <span class='timer'>カウントアップタイマー機能を実装予定！！</span>
          </div>
          <div class='third-box-right'>
            <%= f.text_field :url, class:'caption-input', id:'item-url', placeholder:'参考URL' %>
          </div>
        </div>
        <div class='fourth-box'>
          <span>画像</span>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>

      <div class='input-area'>
        <div class='input-area-left'>
          <%= f.text_area :body, class:'body-input', id:'item-body',placeholder:'テキストを入力', maxlength: '100000' %>
        </div>
        <%# 右側 %>
        <div class='input-area-right'>
          <p>✍️ 開発者メモ</p>
          <p>>>> コンテンツ開発中 >>></P>
        </div>
        <%# // 右側%>
      </div>

      <div class='command-area'>
        <ul class='command-list'>
          <li>
            <%= f.select :status, Item.statuses.keys.to_a, {}, { class:'item-open' } %>
          </li>
          <li>
            <span class='item-preview'>プレビュー</span>
          </li>
          <li>
            <%= f.submit '記録する', class:'output-btn'%>
          </li>
        </ul>
      </div>
    </div> 
  </div>
<% end %>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/items/search.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# Left-side %>
  <div class='top-left-content'>

    <%# Search-Contents %>
    <%= render 'shared/search_contents' %>
    <%# // Search-Contents %>

    <div class='item-list-navi'>
      <p>✏︎「 <%= params[:keyword] %> 」の検索結果</p>
    </div>

    <%# @items リスト展開 %>
    <div id='item-pagenate'>
      <%= render "shared/item-list" %>
    </div>
    <%= link_to_next_page @items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <%# // @items リスト展開 %>   
  </div>
  <%# // Left-side %>
  
  <%# Right-side %>
  <%= render 'shared/right_side' %>
  <%# // Right-side %>
  
</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/items/search.js.erb
$('#item-pagenate').append("<%= escape_javascript(render 'shared/item-list', object: @items) %>")
$("#more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')
) %>");

app/views/items/tag.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# Left-side %>
  <div class='top-left-content'>   
    
    <%# Search-Contents %>
    <%= render 'shared/search_contents' %>
    <%# // Search-Contents %>
    
    <div class='item-list-navi'>
      <p># <%= @tag.name%></p>
    </div>
    
    <%# @items リスト展開 %>
    <div id='item-pagenate'>
      <%= render "shared/item-list" %>
    </div>
    <%= link_to_next_page @items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <%# // @items リスト展開 %>   
  </div>
  <%# // Left-side %>
  
  <%# Right-side %>
    <%= render 'shared/right_side' %>
  <%# // Right-side %>

</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/items/timeline.html.erb
<%= render "shared/header" %>


<%# ゲストログイン用コンテンツ%>
<% unless user_signed_in?%>
  <%= render 'guest'%>
<% end %>
<%# // ゲストログイン用コンテンツ%>

<div class='main'>

  <%# if user_signed_in? %>
    <%# if @user.username == 'guest' %>
      <%# ゲストログイン中！機能が制限されています。 %>
    <%# end %>
  <%# end %>

  <%# Left-side %>
  <div class='top-left-content'>

    <%# Search-Contents %>
    <%= render 'shared/search_contents' %>
    <%# // Search-Contents %>

    <div class='item-list-navi'>
      <p> Time Line</p>
    </div>

    <%# @items リスト展開 %>
    <div id='item-pagenate'>
      <%= render "shared/item-list" %>
    </div>
    <%= link_to_next_page @items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link' %>
    <%# // @items リスト展開 %>   
    
  </div>
  <%# // Left-side%>

  
  <%# Right-side %>
  <%= render 'shared/right_side' %>
  <%# // Right-side %>

</div>

<%# スマホ用コマンド %>
<%= render 'shared/command'%>
<%# // スマホ用コマンド %>

<%= render "shared/footer" %>

app/views/items/timeline.js.erb
$('#item-pagenate').append("<%= escape_javascript(render 'shared/item-list', object: @items) %>")
$("#more-link").replaceWith("<%= escape_javascript(
  link_to_next_page(@items, 'もっと見る', remote: true, class: 'more-link', id: 'more-link')
) %>");